// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9cNFu5uUgyU7bdscBVSJpP

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-shopify";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  commerceProviderComponentProps?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, commerceProviderComponentProps } = props;

  return (
    <CommerceProviderComponent
      {...commerceProviderComponentProps}
      accessToken={
        commerceProviderComponentProps &&
        "accessToken" in commerceProviderComponentProps
          ? commerceProviderComponentProps.accessToken!
          : "0f17ab8b078d7e7541e2c611c89fc85f"
      }
      storeDomain={
        commerceProviderComponentProps &&
        "storeDomain" in commerceProviderComponentProps
          ? commerceProviderComponentProps.storeDomain!
          : "vasta-plasmitc.myshopify.com"
      }
    >
      {children}
    </CommerceProviderComponent>
  );
}
